apiVersion: v1
kind: ReplicationController
metadata:
    name: node
spec:
    replicas: 3
    selector:
        app: nodehttp
    template:
       metadata:
           labels:
              app: nodehttp
       spec:
           containers:
           - name: nodehttp
             image: purecap/nodehttp
             ports:
             - containerPort: 8080
