apiVersion: v1
kind: Pod
metadata:
    name: dnsutils
    labels:
        app: dnsutils
spec:
    containers:
    - image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
      name: dnsutils
      command:
          - sleep
          - "3600"
      imagePullPolicy: IfNotPresent
    restartPolicy: Always
